# Generated by Django 5.2.6 on 2025-11-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='External profile picture URL as fallback', null=True),
        ),
    ]
