# Generated by Django 5.2.6 on 2025-11-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL as fallback', null=True),
        ),
    ]
